# Generated by Django 2.2.1 on 2019-05-27 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=51, unique=True, verbose_name='Name')),
                ('db_type', models.CharField(max_length=51, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='DbTable',
            fields=[
                ('col_name', models.CharField(max_length=51, primary_key=True, serialize=False, verbose_name='Name')),
                ('db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='wind.Database', to_field='db_name')),
            ],
        ),
    ]
