# Generated by Django 2.2.1 on 2019-08-14 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=51, unique=True, verbose_name='Name')),
                ('db_type', models.CharField(max_length=51, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='MapColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='QueryTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Turbine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turbine', models.CharField(max_length=51, unique=True, verbose_name='turbine')),
            ],
        ),
        migrations.CreateModel(
            name='DbTable',
            fields=[
                ('col_name', models.CharField(max_length=51, primary_key=True, serialize=False, verbose_name='Name')),
                ('col_headlist', models.CharField(default='', max_length=5000, verbose_name='col_head')),
                ('db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='wind.Database', to_field='db_name')),
                ('turbine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turbine_type', to='wind.Turbine', to_field='turbine')),
            ],
        ),
    ]
