# Generated by Django 2.2.1 on 2019-05-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbtable',
            name='col_headlist',
            field=models.CharField(default='', max_length=1000, verbose_name='col_head'),
        ),
    ]
