# Generated by Django 2.2.1 on 2019-05-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind', '0002_dbtable_col_headlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbtable',
            name='col_headlist',
            field=models.CharField(default='', max_length=5000, verbose_name='col_head'),
        ),
    ]
