# Generated by Django 2.2.1 on 2019-05-31 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind', '0003_auto_20190528_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('made_on', models.DateField()),
            ],
        ),
    ]
