# Generated by Django 2.2.1 on 2019-05-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind', '0005_auto_20190531_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querytime',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='querytime',
            name='start_time',
            field=models.DateField(),
        ),
    ]
